---
title: "Sequence data for Stellwagen eDNA"
output:
  github_document: default
  pdf_document:
    keep_tex: yes
  html_document:
    toc: yes
    toc_depth: 6
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---

Load data and packages 

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
library(dplyr)

# Read the data
data <- read.delim2("../overall_summary.tsv", sep = "\t", 
                    colClasses = c("character", "numeric", "numeric", "numeric", "character", 
                                   "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))

# Mutate the columns
data <- data %>%
  mutate(
    cutadapt_total_processed = cutadapt_total_processed * 1000,
    cutadapt_passing_filters = cutadapt_passing_filters * 1000
  ) %>%
  mutate(
    # Create a temporary condition
    multiply_condition = DADA2_input < 1000,
    # Apply the condition to each column
    DADA2_input = ifelse(multiply_condition, DADA2_input * 1000, DADA2_input),
    filtered = ifelse(multiply_condition, filtered * 1000, filtered),
    denoisedF = ifelse(multiply_condition, denoisedF * 1000, denoisedF),
    denoisedR = ifelse(multiply_condition, denoisedR * 1000, denoisedR),
    merged = ifelse(multiply_condition, merged * 1000, merged),
    nonchim = ifelse(multiply_condition, nonchim * 1000, nonchim)
  ) %>%
  # Remove the temporary condition column
  select(-multiply_condition)

# Print the updated data
print(data)

length(data %>% subset(percent_nonchim < 0.5))

sum(data$cutadapt_total_processed)
sum(data$denoisedR)
sum(data$merged)
sum(data$nonchim)
```

